# Generated by Django 3.1.7 on 2021-03-25 13:16

from django.db import migrations, models


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Author = apps.get_model('authors', 'Author')
    for person in Author.objects.all():
        person.full_name = '%s %s' % (person.first_name, person.last_name)
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RunPython(combine_names),
    ]
