# Generated by Django 3.1.7 on 2021-03-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
